server {
	listen 80;
	server_name  sobek;
	access_log /var/log/sobek/access.log  main;
	error_log /var/log/sobek/error.log info;
	root /var/www/sobek;

	location / {
		try_files sobek.html =404;
	}

	location /sobek {
		sobek;
		sobek_sign_key 12345678901234567890123456789012
		sobek_cookie_name sobek;
		sobek_ttl 7d;
	}
}

